[package]
name = "skjson"
version = "0.2.0"

[dependencies]
std = { path = "../prelude" }
cli = { path = "../cli" }

[dev-dependencies]
sktest = { path = "../skiplang/sktest" }

[[bin]]
name = "skjson"
main = "SKJSON.main"
