[package]
name = "skargo"
version = "0.3.0"

[dependencies]
std = { path = "../prelude" }
toml = { path = "../toml" }
cli = { path = "../cli" }
semver = { path = "../semver" }

[[bin]]
name = "skargo"
main = "Skargo.main"
