apiVersion: v1
kind: Service
metadata:
  name: rhn-skip
  labels:
    app.kubernetes.io/name: rhn-skip
spec:
  ports:
    - port: 8080
      name: streaming
    - port: 8081
      name: control
  clusterIP: None
  selector:
    app.kubernetes.io/name: rhn-skip
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rhn-skip
  labels:
    app.kubernetes.io/name: rhn-skip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rhn-skip
  serviceName: rhn-skip
  replicas: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhn-skip
    spec:
      imagePullSecrets:
      - name: rhn-skip-ecr-registry
      containers:
      - name: rhn-skip
        image: __ECR__:reactive_service
        command:
        - bash
        - "-c"
        - |
          set -ex
          # use Kubernetes pod index as ID:
          # - index 0 is leader
          # - index >= 1 is follower, using that number in resource prefix
          [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
          id=${BASH_REMATCH[1]}
          ip=$(hostname -i)

          if [[ $id -eq 0 ]]; then
            export SKIP_LEADER=true
            echo "set server skip_control/leader addr $ip port 8081 ; enable server skip_control/leader " | socat stdio tcp4-connect:haproxy-kubernetes-ingress:9999
          else
            export SKIP_FOLLOWER=true
            export SKIP_RESOURCE_PREFIX=follower$id
            export SKIP_LEADER_HOST=rhn-skip-0.rhn-skip.default.svc.cluster.local
            # Self-register both the control and event streaming server with the haproxy load balancer.
            # Calling 'set server' after 'add server' is redundant on initial scale-up, but necessary for subsequent scale-ups when a server of that name already exists.
            # Enabling HAProxy TCP health checks ensures that servers are taken out of rotation when the system scales down or instances crash/disconnect for other reasons.
            echo "\
            add server skip_control/follower$id $ip:8081 check ;\
            set server skip_control/follower$id addr $ip port 8081 ;\
            enable server skip_control/follower$id ;\
            enable health skip_control/follower$id ;\
            add server skip_stream/follower$id $ip:8080 check ;\
            set server skip_stream/follower$id addr $ip port 8080 ;\
            enable server skip_stream/follower$id ;\
            enable health skip_stream/follower$id\
            " | socat stdio tcp4-connect:haproxy-kubernetes-ingress:9999
          fi
          npm start
        ports:
        - name: streaming
          containerPort: 8080
        - name: control
          containerPort: 8081
        env:
        - name: PG_HOST
          value: "rhn-pg.default.svc.cluster.local"
        - name: PG_PORT
          value: "5432"
        readinessProbe:
          exec:
            command:
            - wget
            - "--spider"
            - http://localhost:8081/healthz
          initialDelaySeconds: 1
          periodSeconds: 2
