[package]
name = "skip-runtime-ts"
version = "0.1.0"

[dependencies]
std = { path = "../../skiplang/prelude" }
skjson = { path = "../../skiplang/skjson" }

[dev-dependencies]
sktest = { path = "../../skiplang/sktest" }

[lib]
type = ["cdylib"]
