[package]
name = "skc"
version = "0.2.0"
tests = ["tests/tests.sk"]
test-harness = "SkcTests.main"

[dependencies]
std = { path = "../prelude" }
cli = { path = "../cli" }
arparser = { path = "../arparser" }

[dev-dependencies]
sktest = { path = "../sktest" }

[[bin]]
name = "skc"
main = "main"

[[bin]]
name = "skfmt"
main = "SkipPrinter.main"
