[package]
name = "skdb"
version = "0.1.0"
tests = []  # For now, keep using make. // ["tests/tests.sk"]

[dependencies]
std = { "path" = "../prelude" }
skfs = { "path" = "../skfs" }
cli = { "path" = "../cli" }

[[bin]]
name = "skdb"
main = "SKDB.main"
