[package]
name = "skdb"
version = "0.1.0"

[dependencies]
skdate = { "path" = "../skdate" }
cli = { "path" = "../cli" }
sqlparser = { "path" = "../sqlparser" }

[[bin]]
name = "skdb"
main = "SKDB.main"
