[package]
name = "skdb"
version = "0.1.0"

[lib]
type = ["sklib", "cdylib"]

[dependencies]
std = { path = "../prelude" }
skdate = { path = "../skdate" }
cli = { path = "../cli" }
skjson = { path = "../skjson" }
sqlparser = { path = "../sqlparser" }

[dev-dependencies]
sktest = { path = "../sktest" }

[[bin]]
name = "skdb"
main = "SKDB.main"
