[package]
name = "skdb"
version = "0.2.0"

[dependencies]
std = { path = "../skiplang/prelude" }
skdate = { path = "../skiplang/skdate" }
cli = { path = "../skiplang/cli" }
skjson = { path = "../skiplang/skjson" }
sqlparser = { path = "../skiplang/sqlparser" }

[dev-dependencies]
sktest = { path = "../skiplang/sktest" }

[[bin]]
name = "skdb"
main = "SKDB.main"

[lib]
type = ["cdylib"]
